# These are supported funding model platforms

github: passariello
patreon: passariello
open_collective: # Replace with a single Open Collective username
ko_fi: passariello
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: passariello
issuehunt: passariello
otechie: # Replace with a single Otechie username
custom: ["https://dario.passariello.ca", "https://www.paypal.me/dariopassariello", "https://www.indiegogo.com/individuals/28513718"]
